""
test custom django management commands
"""
from unittest.mock import patch
from psycopg2 import OperationalError as Psycopg2Error

from django.core.management import call_command
from django.db.utils import OperationalError
from django.test import SimpleTestCase

@patch('core.management.commands.wait_for_db.Command.check')
class CommandTests(SimpleTestCase):
    """Test commands."""

    def test_wait_for_db_ready(self,patched_check):
        """test waiting for datbase if database is ready"""
        patched_check.return_value=True
        call_command('wait_for_db')
        patched_check.assert_called_once_with(database=['default'])
    
    @patch('time.sleep')
    def test_wait_for_db_delay(self,patched_sleep,patched_check):
        """test waiting for database when getting opeartional error"""
        patched_check.side_effect=[Psycopg2Error] *2 + [OperationalError]*3+[True]   #so for first 2times we raise psycopg error and next 3times we risr operational error
        
        call_command('wait_for_db')

        self.assertEqual(patched_check.call_count,6)
        # patch_check.assert_called_with(database=['default'])
        patch_check.assert_called_with(databases=['default'])
        
